#+TITLE: Chainweb Transaction Generator
#+AUTHOR: Colin

* Table of Contents :TOC_4_gh:noexport:
- [[#deploying-contracts][Deploying Contracts]]
- [[#sending-transactions][Sending Transactions]]
  - [[#from-the-standard-contracts][From the Standard Contracts]]
  - [[#simple-transactions][Simple Transactions]]
- [[#queries][Queries]]
  - [[#polling][Polling]]
  - [[#listening][Listening]]
- [[#argument-formats][Argument Formats]]
  - [[#list-format][List Format]]

* Deploying Contracts

This can only be perfomed by providing the transaction generator script with the
appropriate .yaml file. Look at either
examples/local-templates/deploy-contracts-template.yaml or
examples/testnet-templates/deploy-contracts-template.yaml for an example of how
to configure this command.

* Sending Transactions

** From the Standard Contracts

This can only be perfomed by providing the transaction generator script with the
appropriate .yaml file. Look at either
examples/local-templates/run-standard-contracts-template.yaml or
examples/testnet-templates/run-standard-contracts-template.yaml for an example
of how to configure this command.

** Simple Transactions

This can only be perfomed by providing the transaction generator
script with the appropriate .yaml file. Look at either
examples/local-templates/run-simple-template.yaml or
examples/testnet-templates/run-simple-template.yaml for an example
of how to configure this command.

* Queries

** Polling

#+begin_src bash
txg --script-command "poll <list of request keys> true|false"
#+end_src

Given a list of request keys, return the results of the transactions
corresponding to each request key. The format for lists is given below. The bool
flag is there to measure the amount of time it takes to poll the request key.
This time is supposed to be logged. This may be removed.

** Listening

#+begin_src bash
  txg --script-command "listen <request key> true|false"
#+end_src

Given a single request key, issue a listen api call with that request key. The
result of the transaction associated with that request key should be returned if
the result is returned before a HTTP timeout. The timeout is set by default to 4
minutes. The bool flag is there to measure the amount of time it takes to listen
upon the request key. This time is supposed to be logged. This may be removed.

* Argument Formats

** List Format

#+begin_example
  [item_1,item_2,...,item_n]
#+end_example

Lists must start with an open bracket ([) and end with a close bracket (]).
There can be whitespace between the open bracket and the first item. There can
be whitespace between the close bracket and the last item. Items are
comma-separated. There can be whitespace before and after the comma.
