resolver: lts-15.7

flags:
  hostaddress:
    with-configuration-tools: true
  configuration-tools:
    remote-configs: false

extra-deps:
  # --- Missing from Stackage --- #
  - configuration-tools-0.5.0
  - fake-0.1.1.3
  - hostaddress-0.1.0.0
  - random-strings-0.1.1.0
  - yet-another-logger-0.4.0

  # --- Transitive Pact Deps --- #
  - ed25519-donna-0.1.1
  - direct-sqlite-2.3.26
  - sbv-8.6
  - prettyprinter-1.6.0
  - github: kadena-io/thyme
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9

  # --- Special Pins --- #
  - github: kadena-io/pact
    commit: ae01cd2ca7549b67f5e9a02dd19509c8975f12c8
