resolver: lts-14.27

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  # --- Transitive Pact Deps --- #
  - ed25519-donna-0.1.1
  - sbv-8.2
  - trifecta-2.1
  - github: kadena-io/thyme
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9

  # --- Transitive Chainweb Deps --- #
  - github: kadena-io/pact
    commit: b59a305b65a8bca5afb82b9c347cca1b71c40211
  - yet-another-logger-0.3.1

  # --- Other Transitive Deps --- #
  - streaming-with-0.2.2.1

  - base64-0.4.1
  - fake-0.1.1.3
  - hostaddress-0.1.0.0
  - optparse-applicative-0.15.1.0
  - random-strings-0.1.1.0

flags:
  hostadress:
    with-configuration-tools: true
  configurationt-tools:
    remote-configs: false
