resolver: lts-14.27

extra-deps:
  # --- Transitive Pact Deps --- #
  - ed25519-donna-0.1.1
  - sbv-8.2
  - trifecta-2.1
  - github: kadena-io/thyme
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9

  # --- Transitive Chainweb Deps --- #
  - github: kadena-io/pact
    commit: b59a305b65a8bca5afb82b9c347cca1b71c40211
  - github: kadena-io/chainweb-storage
    commit: 17a5fb130926582eff081eeb1b94cb6c7097c67a
  - QuickCheck-GenT-0.2.2
  - bloomfilter-2.0.1.0
  - digraph-0.1.0.2
  - fake-0.1.1.3
  - lens-aeson-1.1
  - loglevel-0.1.0.0
  - merkle-log-0.1.0.0
  - paths-0.2.0.0
  - random-strings-0.1.1.0
  - streaming-concurrency-0.3.1.3
  - strict-tuple-0.1.3
  - tls-1.5.4
  - warp-3.3.9
  - warp-tls-3.2.11
  - yet-another-logger-0.3.1

  # --- Other Transitive Deps --- #
  - streaming-with-0.2.2.1

  # --- Custom Pins --- #
  - github: kadena-io/chainweb-node
    commit: 44c58e58fbe34884551bc2cc4d453b498b1b8368
