name: Build and publish application binaries

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  build:
    name: Build master with ${{ matrix.ghc }} / ${{ matrix.cabal }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.8.3', '8.10.1']
        cabal: ['3.2.0.0']
        os: ['ubuntu-18.04']
        cabalcache: ['true']
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.kadena_cabal_cache_aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.kadena_cabal_cache_aws_secret_access_key }}

      # Aritfacts
      ARTIFACT_BUCKET: kadena-cabal-cache
      ARTIFACT_FOLDER: txg

    steps:
    # Setup
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install GHC and Cabal
      uses: actions/setup-haskell@v1.1.0
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}
    - name: Confirm GHC and Cabal installation
      run: |
        ghc --version
        cabal --version
    - name: Install non-Haskell dependencies (ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
          sudo apt-get update
          sudo apt-get install -y git zlib1g-dev libtinfo-dev libsqlite3-dev libz3-dev
    - name: Install non-Haskell dependencies (macOS)
      if: contains(matrix.os, 'mac')
      run: |
        brew update
        brew install z3
        brew install sqlite
    - name: Append cabal.project
      run: |
        cat >> cabal.project <<EOF
        documentation: false
        executable-stripping: True
        library-stripping: True
        constraints:
          neat-interpolation < 0.4
        EOF
    - name: Append cabal.project for GHC-8.10
      if: contains(matrix.ghc, '8.10')
      run : |
        cat >> cabal.project <<EOF
        package pact
          ghc-options: -Wwarn
        package txg
          ghc-options: -Wwarn
        allow-newer:
          *:*
    - uses: actions/cache@v1
      name: Cache dist-newstyle
      with:
        path: dist-newstyle
        key: ${{ matrix.os }}-${{ matrix.ghc }}-dist-newstyle-${{ github.sha }}
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.ghc }}-dist-newstyle-
          ${{ matrix.os }}-${{ matrix.ghc }}-dist-newstyle

    # Build
    - name: Update package database
      run: cabal v2-update
    - name: Configure build
      run: cabal v2-build all --dry-run
    - name: Sync from cabal cache
      if: matrix.cabalcache == 'true'
      uses: larskuhtz/cabal-cache-action@21220b9f6499bb12cb0b4b926d6faa9c46a7b146
      with:
        bucket: "kadena-cabal-cache"
        region: "us-east-1"
        folder: "${{ matrix.os }}"
        aws_access_key_id: "${{ secrets.kadena_cabal_cache_aws_access_key_id }}"
        aws_secret_access_key: "${{ secrets.kadena_cabal_cache_aws_secret_access_key }}"
    - name: Install build dependencies
      run: cabal v2-build --only-dependencies
    - name: Build
      run: cabal v2-build
    - name: Run Tests
      run: cabal v2-test

    # Publish Artifacts
    - name: Prepare artifacts
      run: |
        mkdir -p artifacts/applications
        export VER=$(grep '^version' txg.cabal | sed -e 's/.*: *//')
        cp dist-newstyle/build/*/ghc-${{ matrix.ghc }}/txg-${VER}/x/txg/build/txg/txg artifacts/applications
    - name: Publish applications
      uses: actions/upload-artifact@v1
      with:
        name: txg.${{ matrix.ghc }}.${{ matrix.os }}
        path: artifacts/applications

    # Publish to S3
    - name: Publish applications to S3
      run: |
        export BINFILE="txg.${{ matrix.ghc }}.${{ matrix.os }}.$(git rev-parse --short HEAD).tar.gz"
        tar -C ./artifacts/applications/ -czf $BINFILE txg
        aws s3 cp $BINFILE s3://$ARTIFACT_BUCKET/$ARTIFACT_FOLDER/
        aws s3api put-object-acl --bucket $ARTIFACT_BUCKET --key=$ARTIFACT_FOLDER/$BINFILE --acl public-read
    - name: Link latest-build application in S3
      if: contains(github.ref, 'master')
      run: |
        export BINFILE="txg.${{ matrix.ghc }}.${{ matrix.os }}.$(git rev-parse --short HEAD).tar.gz"
        export LATEST_BINFILE="txg.${{ matrix.ghc }}.${{ matrix.os }}.latest.tar.gz"
        aws s3 cp s3://$ARTIFACT_BUCKET/$ARTIFACT_FOLDER/$BINFILE s3://$ARTIFACT_BUCKET/$ARTIFACT_FOLDER/$LATEST_BINFILE
        aws s3api put-object-acl --bucket $ARTIFACT_BUCKET --key=$ARTIFACT_FOLDER/$LATEST_BINFILE --acl public-read
